v0.8: Visual Feedback Update! (#16)
* Basic infrastructure for visual feedback update with switching between scopes on grill distortion
* Convert FIFO to circular buffer
* Implement input output transfer curve drawing
* Add emphasis view, modify Cmake to not optimise on debug builds lol
* Refactor scope handling, more visual feedback on some components
* Deduplicate computation for emphasis curves, fix distribution, separate into separate files
* Separate scope into h and cpp, make the io plot draw fading history of the signal.
* Fix bug where write locks happen on push and pop (when they not supposed to)
also tweak decay time for io scope
* Add visual feedback for clipping in PostClip and ScopeDataCollector, add ClipIndicator GUI elem. Support oversampling in scope readouts. Fix oversampling knob text error
* Fix issue where queues would desync and visualisations get messed up
* Clipping dot shouldnt be visible if clipper is disabled
* Draw clipping curve
* Text in scope view
* Add visualisation for noise distortions (could be better)
* Initialise clipper with data, make sure it doesnt ever nan propagate or fail randomly
* Improve drawing of clipping levels so its buttery smooth 60fps
* Significantly improve drawing by adding header for visuals, with displayed parameters for each module, draw compressor visuals as well. improve clipping by shading underneath area
* Significantly improve scope detection with schmitt triggering
* Type A drawing and a small bit of cleanup
* Animate knobs when pressed (to indicate interaction)
* Keep the triggered scope view in view for 2 seconds before resetting to default
* Fix build issue from implied variable capture for windows and linux
* Fix linux builds and emit version data for specific Hamburger version into the zip name
* Remove build essential step since we're on Ubuntu 22 now

diff --git a/.github/workflows/Hamburger_Build.yml b/.github/workflows/Hamburger_Build.yml
--- a/.github/workflows/Hamburger_Build.yml
+++ b/.github/workflows/Hamburger_Build.yml
@@ -70,16 +70,16 @@ jobs:
       with:
         node-version: 18
 
-    # thanks to https://forum.juce.com/t/juce-8-linux-issue-with-harfbuzz/61970/3 juce 8 linux builds should work nicely
-    - name: (linux) switch to gcc-11
-      if: startsWith(matrix.os, 'ubuntu')
+    - name: read plugin version
+      id: version
+      shell: bash
       run: |
-        sudo apt install build-essential
-        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
-        sudo apt install g++-11 gcc-11
-        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-11
-        sudo update-alternatives --set gcc /usr/bin/gcc-11
-    
+        VERSION=$(sed -n 's/^[[:space:]]*set(ProjectVersion[[:space:]]*\([0-9][0-9.]*\)).*/\1/p' CMakeLists.txt)
+        if [ -z "$VERSION" ]; then echo "could not parse ProjectVersion from CMakeLists.txt" >&2; exit 1; fi
+        echo "VERSION=$VERSION" >> "$GITHUB_ENV"
+        echo "plugin version: $VERSION"
+
+    # thanks to https://forum.juce.com/t/juce-8-linux-issue-with-harfbuzz/61970/3 juce 8 linux builds should work nicely
     - name: (linux) install juce dependencies
       if: startsWith(matrix.os, 'ubuntu')
       id: juce_dependencies
@@ -247,6 +247,6 @@ jobs:
     
     - uses: actions/upload-artifact@v4
       with:
-        name: ${{env.PLUG}} ${{ matrix.name }}
+        name: ${{env.PLUG}} v${{env.VERSION}} ${{ matrix.name }}
         path: "./gh_artifacts"
         
